#!/usr/bin/env python3
"""Resolve and prepare project-scoped paths for Improve Toolkit."""

from __future__ import annotations

import os
from pathlib import Path


RUNTIME_GITIGNORE_LOCAL = (
    "# Generated by improve-toolkit. Runtime state is local-only; memories are not synced via git.",
    "*",
    "!.gitignore",
)

RUNTIME_GITIGNORE_TRACKED = (
    "# Generated by improve-toolkit. Memory Markdown files stay trackable.",
    "/logs/",
    "/workbench/",
    "/memories/*.lock",
    "/memories/.mem_*.tmp",
    "/memories/.metadata_*.tmp",
    "/memories/.migration_*.tmp",
    "/memories/.summary-state.json",
    "/memories/.summary.dirty",
    "/memories/.summary_*.tmp",
    "/memories/.summary_dirty_*.tmp",
    "/memories/.summary_state_*.tmp",
)

# Backward-compatible alias for the default (local-only) ignore set.
RUNTIME_GITIGNORE_LINES = RUNTIME_GITIGNORE_LOCAL

_TRACK_MEMORIES_VALUES = {"1", "true", "yes", "on"}


def _runtime_gitignore_lines() -> tuple[str, ...]:
    """Return the generated .gitignore lines for the active memory mode."""
    if os.environ.get("IMPROVE_TRACK_MEMORIES", "").strip().lower() in _TRACK_MEMORIES_VALUES:
        return RUNTIME_GITIGNORE_TRACKED
    return RUNTIME_GITIGNORE_LOCAL


def _path_from_env(name: str) -> Path | None:
    value = os.environ.get(name)
    if not value:
        return None
    return Path(value).expanduser()


def get_host() -> str:
    """Return ``codex`` or ``claude`` for the current plugin host."""
    explicit = os.environ.get("IMPROVE_HOST", "").strip().lower()
    if explicit in {"codex", "claude"}:
        return explicit

    # PLUGIN_ROOT is a Codex-specific extension. Codex also exports the
    # CLAUDE_PLUGIN_ROOT alias, so test the Codex variable first.
    if os.environ.get("PLUGIN_ROOT"):
        return "codex"
    if os.environ.get("CLAUDE_PROJECT_DIR"):
        return "claude"
    if os.environ.get("CODEX_HOME"):
        return "codex"
    return "claude"


def get_project_dir() -> Path:
    """Return the project whose session owns the plugin state."""
    return (
        _path_from_env("IMPROVE_PROJECT_DIR")
        or _path_from_env("CLAUDE_PROJECT_DIR")
        or Path.cwd()
    )


def get_data_home(project_dir: Path | str | None = None) -> Path:
    """Return the shared root for memories, logs, and workbench files."""
    override = _path_from_env("IMPROVE_DATA_DIR")
    if override is not None:
        return override

    project_dir = Path(project_dir).expanduser() if project_dir is not None else get_project_dir()
    return project_dir / ".improve-toolkit"


def prepare_data_home(project_dir: Path | str | None = None) -> Path:
    """Create the shared runtime root and its local ignore rules.

    By default the nested .gitignore ignores the entire runtime directory, so
    memories, logs, and workbench files stay local-only and are not synced via
    git. Projects that want memory version-controlled can set
    IMPROVE_TRACK_MEMORIES=1 to switch to narrow rules that keep MEMORY.md and
    USER.md trackable. The generated section is rebuilt when the mode changes;
    existing custom rules are preserved.
    """
    data_home = get_data_home(project_dir)
    data_home.mkdir(parents=True, exist_ok=True)
    active = _runtime_gitignore_lines()
    ignore_path = data_home / ".gitignore"
    existing = ignore_path.read_text(encoding="utf-8") if ignore_path.exists() else ""
    existing_lines = existing.splitlines()
    generated = set(RUNTIME_GITIGNORE_LOCAL) | set(RUNTIME_GITIGNORE_TRACKED)
    user_lines = [line for line in existing_lines if line not in generated]
    new_text = "\n".join(user_lines + list(active))
    if new_text and not new_text.endswith("\n"):
        new_text += "\n"
    if new_text != existing:
        ignore_path.write_text(new_text, encoding="utf-8")
    return data_home


def get_memories_dir(project_dir: Path | str | None = None) -> Path:
    """Return the shared, project-scoped memory directory.

    Memory is intentionally host-neutral so Codex and Claude Code see the same
    MEMORY.md and USER.md files.  IMPROVE_DATA_DIR keeps its historical
    all-runtime-state override semantics; IMPROVE_MEMORY_DIR can override only
    the memory store.
    """
    override = _path_from_env("IMPROVE_MEMORY_DIR")
    if override is not None:
        return override

    return get_data_home(project_dir) / "memories"


def get_legacy_memories_dirs(project_dir: Path | str | None = None) -> tuple[Path, ...]:
    """Return pre-shared memory locations eligible for one-time migration."""
    if _path_from_env("IMPROVE_MEMORY_DIR") or _path_from_env("IMPROVE_DATA_DIR"):
        return ()

    project_dir = Path(project_dir).expanduser() if project_dir is not None else get_project_dir()
    return (
        project_dir / ".claude" / "memories",
        project_dir / ".codex" / "improve-toolkit" / "memories",
    )
