#!/usr/bin/env python3
"""Resolve and prepare project-scoped paths for Improve Toolkit."""

from __future__ import annotations

import os
from pathlib import Path


RUNTIME_GITIGNORE_LINES = (
    "# Generated by improve-toolkit. Memory Markdown files stay trackable.",
    "/logs/",
    "/workbench/",
    "/memories/*.lock",
    "/memories/.mem_*.tmp",
    "/memories/.migration_*.tmp",
)


def _path_from_env(name: str) -> Path | None:
    value = os.environ.get(name)
    if not value:
        return None
    return Path(value).expanduser()


def get_host() -> str:
    """Return ``codex`` or ``claude`` for the current plugin host."""
    explicit = os.environ.get("IMPROVE_HOST", "").strip().lower()
    if explicit in {"codex", "claude"}:
        return explicit

    # PLUGIN_ROOT is a Codex-specific extension. Codex also exports the
    # CLAUDE_PLUGIN_ROOT alias, so test the Codex variable first.
    if os.environ.get("PLUGIN_ROOT"):
        return "codex"
    if os.environ.get("CLAUDE_PROJECT_DIR"):
        return "claude"
    if os.environ.get("CODEX_HOME"):
        return "codex"
    return "claude"


def get_project_dir() -> Path:
    """Return the project whose session owns the plugin state."""
    return (
        _path_from_env("IMPROVE_PROJECT_DIR")
        or _path_from_env("CLAUDE_PROJECT_DIR")
        or Path.cwd()
    )


def get_data_home(project_dir: Path | str | None = None) -> Path:
    """Return the shared root for memories, logs, and workbench files."""
    override = _path_from_env("IMPROVE_DATA_DIR")
    if override is not None:
        return override

    project_dir = Path(project_dir).expanduser() if project_dir is not None else get_project_dir()
    return project_dir / ".improve-toolkit"


def prepare_data_home(project_dir: Path | str | None = None) -> Path:
    """Create the shared runtime root and its local ignore rules.

    The nested .gitignore keeps logs, workbench files, locks, and abandoned
    atomic-write temp files out of Git while leaving MEMORY.md and USER.md
    visible for version control. Existing custom rules are preserved.
    """
    data_home = get_data_home(project_dir)
    data_home.mkdir(parents=True, exist_ok=True)
    ignore_path = data_home / ".gitignore"
    existing = ignore_path.read_text(encoding="utf-8") if ignore_path.exists() else ""
    existing_lines = set(existing.splitlines())
    missing = [line for line in RUNTIME_GITIGNORE_LINES if line not in existing_lines]
    if missing:
        separator = "" if not existing or existing.endswith("\n") else "\n"
        with open(ignore_path, "a", encoding="utf-8") as handle:
            handle.write(separator + "\n".join(missing) + "\n")
    return data_home


def get_memories_dir(project_dir: Path | str | None = None) -> Path:
    """Return the shared, project-scoped memory directory.

    Memory is intentionally host-neutral so Codex and Claude Code see the same
    MEMORY.md and USER.md files.  IMPROVE_DATA_DIR keeps its historical
    all-runtime-state override semantics; IMPROVE_MEMORY_DIR can override only
    the memory store.
    """
    override = _path_from_env("IMPROVE_MEMORY_DIR")
    if override is not None:
        return override

    return get_data_home(project_dir) / "memories"


def get_legacy_memories_dirs(project_dir: Path | str | None = None) -> tuple[Path, ...]:
    """Return pre-shared memory locations eligible for one-time migration."""
    if _path_from_env("IMPROVE_MEMORY_DIR") or _path_from_env("IMPROVE_DATA_DIR"):
        return ()

    project_dir = Path(project_dir).expanduser() if project_dir is not None else get_project_dir()
    return (
        project_dir / ".claude" / "memories",
        project_dir / ".codex" / "improve-toolkit" / "memories",
    )
